--- !ditz.rubyforge.org,2008-03-06/issue 
title: assert failure with 'break' from inside a with stmt which is inside a do-while loop
desc: ""
type: :task
component: duk
release: v0.10
reporter: Sami Vaarala <sami.vaarala@iki.fi>
status: :closed
disposition: :fixed
creation_time: 2014-04-13 15:43:06.638809 Z
references: []

id: 50b0f0f06ad6d72c9a72cde0b89c080f92212a2d
log_events: 
- - 2014-04-13 15:43:06.780647 Z
  - Sami Vaarala <sami.vaarala@iki.fi>
  - created
  - ""
- - 2014-04-13 15:56:18.356910 Z
  - Sami Vaarala <sami.vaarala@iki.fi>
  - commented
  - See test-bug-dowhile-with-break.js
- - 2014-04-13 16:26:19.331437 Z
  - Sami Vaarala <sami.vaarala@iki.fi>
  - closed with disposition fixed
  - ""
